[package]
name = "simulabra-pylib"
version = "0.1.0"
edition = "2021"

[lib]
name = "simulabra"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "*"
features = ["extension-module"]

[workspace]
